version: "3"
services:
  qflex:
    image: qflex
    container_name: qflex
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - OMP_NUM_THREADS=4
  qflex-tests:
    image: qflex-tests
    container_name: qflex-tests
    build:
      context: ./
      dockerfile: tests/Dockerfile
    environment:
      - OMP_NUM_THREADS=4
    depends_on:
    - qflex
  qflex-py-tests:
    image: qflex-py-tests
    container_name: qflex-py-tests
    build:
      context: ./
      dockerfile: python/Dockerfile
    environment:
      - OMP_NUM_THREADS=4
    depends_on:
    - qflex
